//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Save_Pictures_Find.java
//  @ Date : 2018-01-28
//  @ Author : 
//
//




public class Save_Pictures_Find {
	public static void main(String[] args) {
	new GUI_View(); 
	}
}
